teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 5
      y: 4
    scale_linear:
      x: 1.0
      y: 1.0
      
    scale_linear_turbo:
      x: 2.0
      y: 2.0
    
    axis_angular:
      roll: 0
      pitch: 1
      yaw: 2

    scale_angular:
      roll: 1.0
      pitch: 1.0
      yaw: 2.0

    enable_button: 1
    enable_turbo_button: 0
